ci

diff --git a/docker/pypgstac/bin/test b/docker/pypgstac/bin/test
--- a/docker/pypgstac/bin/test
+++ b/docker/pypgstac/bin/test
@@ -1,5 +1,8 @@
 #!/bin/bash
 set -e
+SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+export SRCDIR=$SCRIPT_DIR/../../../src
+export PGSTACDIR=$SRCDIR/pgstac
 
 if [[ "${CI}" ]]; then
     set -x
@@ -15,7 +18,7 @@ This scripts is meant to be run inside the dev container.
 }
 
 function setuptestdb(){
-    cd /opt/src/pgstac
+    cd $PGSTACDIR
     psql -X -q -v ON_ERROR_STOP=1 <<EOSQL
 DROP DATABASE IF EXISTS pgstac_test_db_template;
 CREATE DATABASE pgstac_test_db_template;
@@ -27,13 +30,13 @@ EOSQL
 }
 
 function test_formatting(){
-    cd /opt/src/pypgstac
+    cd $SRCDIR/pypgstac
 
     echo "Running ruff"
-    ruff pypgstac tests
+    ruff python tests
 
     echo "Running mypy"
-    mypy pypgstac
+    mypy python
 
     echo "Checking if there are any staged migrations."
     find pypgstac/migrations | grep 'staged' && { echo "There are staged migrations in pypgstac/migrations. Please check migrations and remove staged suffix."; exit 1; }
@@ -46,20 +49,20 @@ function test_formatting(){
     fi
 
     echo "Checking whether base sql migration exists for pypgstac version."
-    [ -f pypgstac/migrations/pgstac."${VERSION}".sql ] || { echo "****FAIL No Migration exists pypgstac/migrations/pgstac.${VERSION}.sql"; exit 1; }
+    [ -f $SRCDIR/pgstac/migrations/pgstac."${VERSION}".sql ] || { echo "****FAIL No Migration exists pypgstac/migrations/pgstac.${VERSION}.sql"; exit 1; }
 
     echo "Congratulations! All formatting tests pass."
 }
 
 function test_pgtap(){
-cd /opt/src/pgstac
+cd $PGSTACDIR
 TEMPLATEDB=${1:-pgstac_test_db_template}
 psql -X -q -v ON_ERROR_STOP=1 <<EOSQL
 DROP DATABASE IF EXISTS pgstac_test_pgtap WITH (force);
 CREATE DATABASE pgstac_test_pgtap TEMPLATE $TEMPLATEDB;
 ALTER DATABASE pgstac_test_pgtap SET client_min_messages to $CLIENTMESSAGES;
 EOSQL
-TESTOUTPUT=$(psql -X -q -v ON_ERROR_STOP=1 -f /opt/src/pgstac/tests/pgtap.sql pgstac_test_pgtap)
+TESTOUTPUT=$(psql -X -q -v ON_ERROR_STOP=1 -f $PGSTACDIR/tests/pgtap.sql pgstac_test_pgtap)
 psql -X -q -v ON_ERROR_STOP=1 <<EOSQL
 DROP DATABASE IF EXISTS pgstac_test_pgtap WITH (force);
 EOSQL
@@ -75,7 +78,7 @@ fi
 
 function test_basicsql(){
 TEMPLATEDB=${1:-pgstac_test_db_template}
-cd /opt/src/pgstac
+cd $PGSTACDIR
 psql -X -q -v ON_ERROR_STOP=1 <<EOSQL
 DROP DATABASE IF EXISTS pgstac_test_basicsql WITH (force);
 CREATE DATABASE pgstac_test_basicsql TEMPLATE $TEMPLATEDB;
@@ -93,7 +96,7 @@ TMPFILE=$(mktemp)
 trap 'rm "$TMPFILE"' 0 2 3 15
 
 SQLOUTFILE=${SQLFILE}.out
-cd /opt/src/pgstac
+cd $PGSTACDIR
 
 echo "Running basic tests for $SQLFILE"
 psql -X -t -a -v ON_ERROR_STOP=1 pgstac_test_basicsql \
@@ -111,7 +114,7 @@ psql -X -q -c "DROP DATABASE IF EXISTS pgstac_test_basicsql WITH (force);";
 function test_pypgstac(){
 [[ $MESSAGELOG == 1 ]] && VERBOSE="-vvv"
 TEMPLATEDB=${1:-pgstac_test_db_template}
-    cd /opt/src/pypgstac
+    cd $SRCDIR/pypgstac
     psql -X -q -v ON_ERROR_STOP=1 <<EOSQL
 DROP DATABASE IF EXISTS pgstac_test_pypgstac WITH (force);
 CREATE DATABASE pgstac_test_pypgstac TEMPLATE $TEMPLATEDB;
