Rust Hydration (#201)
* Update Docker with Rust tooling, split into database and pypgstac as separate images

* update pypgstac to add rust hydration module

* cleanup

* add private json object to items and collections. add geometry, datetime, and end_datetime generated fields to collections

* update changelog

* update ci

* update workflow for release

* fix test on incremental migrations

* switch from serde to pyo3

* fixes from PR review

* fix: remove cargo registry

This fixes a permissions error when running the test scripts as non-root.

* deps: track Cargo.lock

* fix: small rust cleanups

---------

Co-authored-by: Pete Gadomski <pete.gadomski@gmail.com>

diff --git a/docker/pypgstac/bin/test b/docker/pypgstac/bin/test
--- a/docker/pypgstac/bin/test
+++ b/docker/pypgstac/bin/test
@@ -1,14 +1,12 @@
 #!/bin/bash
 set -e
+SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+export SRCDIR=$SCRIPT_DIR/../../../src
+export PGSTACDIR=$SRCDIR/pgstac
 
 if [[ "${CI}" ]]; then
     set -x
 fi
-if [ ! $PGSTACDOCKER == 1 ]; then
-    echo "This script should only be run within pgstac docker"; exit 1;
-fi
-
-source $(dirname $0)/tmpdb
 
 function usage() {
     echo -n \
@@ -19,37 +17,52 @@ This scripts is meant to be run inside the dev container.
 "
 }
 
+function setuptestdb(){
+    cd $PGSTACDIR
+    psql -X -q -v ON_ERROR_STOP=1 <<EOSQL
+DROP DATABASE IF EXISTS pgstac_test_db_template;
+CREATE DATABASE pgstac_test_db_template;
+ALTER DATABASE pgstac_test_db_template SET CLIENT_MIN_MESSAGES TO WARNING;
+ALTER DATABASE pgstac_test_db_template SET SEARCH_PATH to pgstac, public;
+\connect pgstac_test_db_template;
+\i pgstac.sql
+EOSQL
+}
 
 function test_formatting(){
-    cd /opt/src/pypgstac
+    cd $SRCDIR/pypgstac
 
     echo "Running ruff"
-    ruff --cache-dir=/tmp/.ruff pypgstac tests
+    ruff python tests
 
     echo "Running mypy"
-    mypy --cache-dir=/tmp/.mypy pypgstac
+    mypy python
 
     echo "Checking if there are any staged migrations."
-    find pypgstac/migrations | grep 'staged' && { echo "There are staged migrations in pypgstac/migrations. Please check migrations and remove staged suffix."; exit 1; }
+    find $SRCDIR/pgstac/migrations | grep 'staged' && { echo "There are staged migrations in pypgstac/migrations. Please check migrations and remove staged suffix."; exit 1; }
 
 
     VERSION=$(python -c "from pypgstac.version import __version__; print(__version__)")
     echo $VERSION
+    if echo $VERSION | grep "dev"; then
+        VERSION="unreleased"
+    fi
 
     echo "Checking whether base sql migration exists for pypgstac version."
-    [ -f pypgstac/migrations/pgstac."${VERSION}".sql ] || { echo "****FAIL No Migration exists pypgstac/migrations/pgstac.${VERSION}.sql"; exit 1; }
+    [ -f $SRCDIR/pgstac/migrations/pgstac."${VERSION}".sql ] || { echo "****FAIL No Migration exists pypgstac/migrations/pgstac.${VERSION}.sql"; exit 1; }
 
     echo "Congratulations! All formatting tests pass."
 }
 
 function test_pgtap(){
-cd /opt/src/pgstac
+cd $PGSTACDIR
 TEMPLATEDB=${1:-pgstac_test_db_template}
 psql -X -q -v ON_ERROR_STOP=1 <<EOSQL
+DROP DATABASE IF EXISTS pgstac_test_pgtap WITH (force);
 CREATE DATABASE pgstac_test_pgtap TEMPLATE $TEMPLATEDB;
 ALTER DATABASE pgstac_test_pgtap SET client_min_messages to $CLIENTMESSAGES;
 EOSQL
-TESTOUTPUT=$(psql -X -q -v ON_ERROR_STOP=1 -f /opt/src/pgstac/tests/pgtap.sql pgstac_test_pgtap)
+TESTOUTPUT=$(psql -X -q -v ON_ERROR_STOP=1 -f $PGSTACDIR/tests/pgtap.sql pgstac_test_pgtap)
 psql -X -q -v ON_ERROR_STOP=1 <<EOSQL
 DROP DATABASE IF EXISTS pgstac_test_pgtap WITH (force);
 EOSQL
@@ -65,8 +78,9 @@ fi
 
 function test_basicsql(){
 TEMPLATEDB=${1:-pgstac_test_db_template}
-cd /opt/src/pgstac
+cd $PGSTACDIR
 psql -X -q -v ON_ERROR_STOP=1 <<EOSQL
+DROP DATABASE IF EXISTS pgstac_test_basicsql WITH (force);
 CREATE DATABASE pgstac_test_basicsql TEMPLATE $TEMPLATEDB;
 ALTER DATABASE pgstac_test_basicsql SET search_path to pgstac, public;
 ALTER DATABASE pgstac_test_basicsql SET client_min_messages to $CLIENTMESSAGES;
@@ -82,7 +96,7 @@ TMPFILE=$(mktemp)
 trap 'rm "$TMPFILE"' 0 2 3 15
 
 SQLOUTFILE=${SQLFILE}.out
-cd /opt/src/pgstac
+cd $PGSTACDIR
 
 echo "Running basic tests for $SQLFILE"
 psql -X -t -a -v ON_ERROR_STOP=1 pgstac_test_basicsql \
@@ -94,28 +108,41 @@ psql -X -t -a -v ON_ERROR_STOP=1 pgstac_test_basicsql \
 diff -Z -b -w -B --strip-trailing-cr --suppress-blank-empty -C 1 "$TMPFILE" $SQLOUTFILE && echo "TEST $SQLFILE PASSED" || { echo "***TEST FOR $SQLFILE FAILED***"; exit 1; }
 
 done
-psql -X -q -c "DROP DATABASE pgstac_test_basicsql WITH (force)";
+psql -X -q -c "DROP DATABASE IF EXISTS pgstac_test_basicsql WITH (force);";
 }
 
 function test_pypgstac(){
+[[ $MESSAGELOG == 1 ]] && VERBOSE="-vvv"
 TEMPLATEDB=${1:-pgstac_test_db_template}
-    cd /opt/src/pypgstac
+    cd $SRCDIR/pypgstac
+    python -m venv venv
+    source venv/bin/activate
+    pip install --cache /tmp/.pipcache --upgrade pip
+    pip install --cache /tmp/.pipcache -e . --no-deps
     psql -X -q -v ON_ERROR_STOP=1 <<EOSQL
+DROP DATABASE IF EXISTS pgstac_test_pypgstac WITH (force);
 CREATE DATABASE pgstac_test_pypgstac TEMPLATE $TEMPLATEDB;
 ALTER DATABASE pgstac_test_pypgstac SET client_min_messages to $CLIENTMESSAGES;
 EOSQL
-    pytest tests -o cache_dir=/tmp/.pytest_cache
-    psql -X -q -c "DROP DATABASE pgstac_test_pypgstac WITH (force)";
+    pytest tests $VERBOSE
+    psql -X -q -c "DROP DATABASE IF EXISTS pgstac_test_pypgstac WITH (force)";
 }
 
 function test_migrations(){
     psql -X -q -v ON_ERROR_STOP=1 <<EOSQL
+DROP DATABASE IF EXISTS pgstac_test_migration WITH (force);
 CREATE DATABASE pgstac_test_migration;
 ALTER DATABASE pgstac_test_migration SET search_path to pgstac, public;
 ALTER DATABASE pgstac_test_migration SET client_min_messages to $CLIENTMESSAGES;
 EOSQL
     export PGDATABASE=pgstac_test_migration
     echo "Migrating from version 0.1.9"
+    cd $SRCDIR/pypgstac
+    python -m venv venv
+    source venv/bin/activate
+    pip install --cache /tmp/.pipcache --upgrade pip
+    pip install --cache /tmp/.pipcache -e .[dev,test,psycopg]
+
     pypgstac migrate --toversion 0.1.9
     pypgstac --version
 
@@ -126,7 +153,7 @@ EOSQL
     test_pgtap pgstac_test_migration
     test_basicsql pgstac_test_migration
     test_pypgstac pgstac_test_migration
-    psql -X -q -c "DROP DATABASE pgstac_test_migration WITH (force)" postgres
+    psql -X -q -c "DROP DATABASE IF EXISTS pgstac_test_migration WITH (force);" postgres
 }
 
 FORMATTING=0
