Enforce version in scripts/stageversion

diff --git a/scripts/bin/stageversion b/scripts/bin/stageversion
--- a/scripts/bin/stageversion
+++ b/scripts/bin/stageversion
@@ -8,8 +8,8 @@ fi
 
 function usage() {
     echo -n \
-        "Usage: $(basename "$0") version or rule
-Format code.
+        "Usage: $(basename "$0") VERSION
+Stage migrations for VERSION
 
 This scripts is meant to be run inside the dev container.
 
@@ -17,6 +17,12 @@ This scripts is meant to be run inside the dev container.
 }
 
 VERSION=$1
+
+if [[ -z "${VERSION}" ]]; then
+    echo "ERROR: Must supply a version."
+    usage
+    exit 1
+fi
 
 
 if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
