Version 0.6.2 (#113)
* Enforce version in scripts/stageversion

* Update to version 0.6.2

* Update CHANGELOG for 0.6.2

diff --git a/scripts/stageversion b/scripts/stageversion
--- a/scripts/stageversion
+++ b/scripts/stageversion
@@ -8,14 +8,23 @@ fi
 
 function usage() {
     echo -n \
-        "Usage: $(basename "$0") version string or rule(patch,minor,major)
-Create a new tag
+        "Usage: $(basename "$0") VERSION
+
+Stage migration for VERSION
 
 "
 }
 
+VERSION=$1
+
+if [[ -z "${VERSION}" ]]; then
+    echo "ERROR: Must supply a version."
+    usage
+    exit 1
+fi
+
 if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
     echo "Updating Version..."
-    docker-compose run --rm dev scripts/bin/stageversion $1
+    docker-compose run --rm dev scripts/bin/stageversion ${VERSION}
     docker-compose exec -T database scripts/bin/stageversiondb
 fi
